export const categories  = [
  { id: 478, name: 'Accessories' },
  { id: 149, name: 'Art' },
  { id: 521, name: 'Auto News' },
  { id: 477, name: 'Bag' },
  { id: 171, name: 'Beauty' },
  { id: 2066, name: 'Bespoke' },
  { id: 2067, name: 'Bespoke' },
  { id: 2205, name: 'Boutiques' },
  { id: 1185, name: 'Business' },
  { id: 2385, name: 'Celebrities' },
  { id: 162, name: 'Cookbook' },
  { id: 163, name: 'Culture' },
  { id: 161, name: 'Dining' },
  { id: 520, name: 'Drive' },
  { id: 2107, name: 'Entrepreneur' },
  { id: 164, name: 'Events' },
  { id: 2068, name: 'Exhibition' },
  { id: 522, name: 'Experience' },
  { id: 170, name: 'Fashion' },
  { id: 1310, name: 'Fashion Week' },
  { id: 151, name: 'Food' },
  { id: 2213, name: 'Grooming' },
  { id: 167, name: 'Health' },
  { id: 160, name: 'Holidays' },
  { id: 159, name: 'Hotels' },
  { id: 2106, name: 'Influencer' },
  { id: 8, name: 'Interviews' },
  { id: 165, name: 'Jewellery' },
  { id: 2114, name: 'Luxury' },
  { id: 156, name: 'Men' },
  { id: 152, name: 'News' },
  { id: 2207, name: 'Pop Culture' },
  { id: 154, name: 'Shoots' },
  { id: 150, name: 'Travel' },
  { id: 5, name: 'Trends' },
  { id: 172, name: 'True Story' },
  { id: 166, name: 'uncat' },
  { id: 2363, name: 'Watches' },
  { id: 155, name: 'Women' },
]
